spring:
  datasource:
    url: jdbc:mariadb://localhost:3310/sid?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  redis:
    host: localhost
    port: 6380
    password:

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace



jwt:
  secret: fdskfnsklfnewfnlwekfnlkewnfklewnflkwenflkew



webmvc:
  cors:
    allowedOrigins:
      http://localhost:8080
